name: ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  
  # curved navigationbar
  curved_navigation_bar: ^1.0.6

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Uncomment and use if needed
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  # Uncomment and use if needed
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 800

# # Separate section for flutter_native_splash configuration
# flutter_native_splash:
#   color: "#FFFFFF" # Background color of the splash screen
#   color_dark: "#272727" # Dark theme splash background color
#   image: assets/logos/t-store-splash-logo-black.png # Path to your splash screen logo image
#   image_dark: assets/logos/t-store-splash-logo-white.png # Path to dark theme logo
#   android: true
#   web: false
